In [3]:
import numpy as np
import pandas as pd

pima_df = pd.read_csv('/Users/briannabrowning/Desktop/pandas sheets/diabetes_uncleaned_data.csv')

pima_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,FALSE
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,FALSE
2,8.0,59.0,109,18,739,59.1,1.769,91.0,TRUE
3,11.0,132.0,83,11,376,4.1,2.772,NaN,TRUE
4,10.0,165.0,48,37,737,39.4,0.729,73.0,FALSE

In [4]:
# Question 1:  In your Jupyter Notebook, find columns with missing data.

pima_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               890 non-null    float64
 1   Glucose                   988 non-null    float64
 2   BloodPressure             982 non-null    object
 3   SkinThickness             1004 non-null   int64
 4   Insulin                   1004 non-null   int64
 5   BMI                       1003 non-null   object
 6   DiabetesPedigreeFunction  1004 non-null   float64
 7   Age                       982 non-null    float64
 8   Outcome                   1004 non-null   object
dtypes: float64(4), int64(2), object(3)
memory usage: 70.7+ KB

In [7]:
# Question 2:  Write code to remove rows with missing data
# save the new dataframe as pima_missing_fixed_df.

pima_missing_fixed_df = pima_df.dropna()

pima_missing_fixed_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,FALSE
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,FALSE
2,8.0,59.0,109,18,739,59.1,1.769,91.0,TRUE
4,10.0,165.0,48,37,737,39.4,0.729,73.0,FALSE
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,TRUE

In [9]:

pima_missing_fixed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 840 entries, 0 to 1003
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               840 non-null    float64
 1   Glucose                   840 non-null    float64
 2   BloodPressure             840 non-null    object
 3   SkinThickness             840 non-null    int64
 4   Insulin                   840 non-null    int64
 5   BMI                       840 non-null    object
 6   DiabetesPedigreeFunction  840 non-null    float64
 7   Age                       840 non-null    float64
 8   Outcome                   840 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 65.6+ KB

In [11]:
# Question 3:  Print out the number of rows in the dataframe.

pima_missing_fixed_df.shape[0]

840

In [ ]:
# Question 4: why could this be a problem? 
# What other methods could you use in this situation? 


# If we drop too many null rows, it can skew our data, outputting inaccurate results. 
# Other methods: 
    # replace missing values with estimates
    # keep rows in that have less than a specifced amount of nulls

In [ ]:
PART 3

In [14]:
# Question 1:  In your Jupyter Notebook, find the rows of duplicated data in the
# pima_missing_fixed_df and print them.  

pima_missing_fixed_df.duplicated()

0       False
1       False
2       False
4       False
5       False
        ...
998     False
999      True
1001    False
1002    False
1003     True
Length: 840, dtype: bool

In [18]:
# Question 2:  Write code to remove the duplicate rows and save 
# the new dataframe as pima_dedupped_df

pima_dedupped_df = pima_missing_fixed_df.drop_duplicates()

pima_dedupped_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,FALSE
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,FALSE
2,8.0,59.0,109,18,739,59.1,1.769,91.0,TRUE
4,10.0,165.0,48,37,737,39.4,0.729,73.0,FALSE
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,TRUE

In [19]:
# Question 3: Print out the number of rows in the dataframe

pima_dedupped_df.shape[0]

836

In [ ]:
PART 4 Mis-typed Columns/Broken Data

In [20]:
# Question 1:  
# Find the columns where most of the data seems to be one type of data, and there seems to be a data error. 
# In the markdown, after exploring in code, add a markdown cell discussing which columns have the data error. 

pima_dedupped_df.value_counts()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age    Outcome
-100.0       142.0    88             39             82       42.7  1.369                     148.0  TRUE       1
 8.0         172.0    101            6              838      20.1  2.258                     104.0  FALSE      1
 9.0         54.0     107            50             421      59.6  2.845                     106.0  FALSE      1
             57.0     31             40             368      38.2  2.372                     142.0  TRUE       1
             73.0     32             11             544      24.2  0.869                     145.0  FALSE      1
                                                                                                              ..
 5.0         4.0      68             10             28       17.4  2.998                     65.0   TRUE       1
             14.0     104            3              555      32.6  2.302                     45.0   FALSE      1
                      77             26             465      11.3  1.737                     125.0  TRUE       1
             15.0     63             33             792      6.3   1.041                     43.0   TRUE       1
 13.0        196.0    84             43             666      38.7  1.138                     52.0   TRUE       1
Name: count, Length: 836, dtype: int64

In [21]:
# Question 2: Remove the rows with data errors

pima_dedupped_df.dropna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,FALSE
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,FALSE
2,8.0,59.0,109,18,739,59.1,1.769,91.0,TRUE
4,10.0,165.0,48,37,737,39.4,0.729,73.0,FALSE
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,TRUE
...,...,...,...,...,...,...,...,...,...
996,6.0,117.0,91,28,212,1.0,1.969,137.0,FALSE
997,13.0,163.0,10,37,457,8.0,2.400,125.0,TRUE
998,6.0,110.0,26,27,590,20.8,1.185,95.0,FALSE
1001,4.0,80.0,24,6,268,48.9,0.989,81.0,TRUE
1002,3.0,142.0,Error,10,299,4.8,2.411,71.0,TRUE

In [23]:
# Question 3: After the data is fixed in your columns change the columns to the 
# correct type and save this as the pima_fixed_columns_df.

def fix_columns(df):
    df_fixed = df
    return df_fixed
pima_fixed_columns_df = fix_columns(pima_dedupped_df)

pima_fixed_columns_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,FALSE
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,FALSE
2,8.0,59.0,109,18,739,59.1,1.769,91.0,TRUE
4,10.0,165.0,48,37,737,39.4,0.729,73.0,FALSE
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,TRUE

In [24]:
# Question 4: Run pima_fixed_columns_df.info() to confirm the columns have changed.

pima_fixed_columns_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 836 entries, 0 to 1002
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               836 non-null    float64
 1   Glucose                   836 non-null    float64
 2   BloodPressure             836 non-null    object
 3   SkinThickness             836 non-null    int64
 4   Insulin                   836 non-null    int64
 5   BMI                       836 non-null    object
 6   DiabetesPedigreeFunction  836 non-null    float64
 7   Age                       836 non-null    float64
 8   Outcome                   836 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 65.3+ KB

In [ ]:
PART 5: Outliers

In [38]:
# Question 1: Print out the Outliers in each column in the pima_fixed_columns_df dataframe
# use the IQR method of outlier detection.

def is_outlier(pima_fixed_columns_df):
    Q1 = pima_fixed_columns_df.quantile(.25)
    Q3 = pima_fixed_columns_df.quantile(.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    return pima_fixed_columns_df[~pima_fixed_columns_df.between(lower_bound, upper_bound)]

In [43]:
# Question 2: Use loc to remove outliers in each of the columns that have outliers, 
# save this as pima_outlier_removed_df.

outliers = pima_fixed_columns_df.apply(is_outlier)

# create copy of df
pima_outlier_removed_df = pima_fixed_columns_df.copy()

for column in outliers_in_column.columns:
    outliers = outliers_in_column
    pima_outlier_removed_df.loc[outliers.index[outliers], column] = None

orint(pima_outlier_removed_df)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [44]:
# Question 3:  Print out the row count in the pima_outlier_removed_df and confirm this number is correct.

pima_outlier_removed_df.shape[0]

AttributeError: 'NoneType' object has no attribute 'shape'

In [45]:
pima_outlier_removed_df.head()

AttributeError: 'NoneType' object has no attribute 'head'